name: tf-checks
permissions:
  id-token: write
on:
  pull_request:
jobs:
  event_bus_archive:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/event_bus_archive/'
      provider: aws
    secrets: 
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  event_rule_target:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/event_rule_target/'
      provider: aws
    secrets: 
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
